server:
  port: ${SERVER_PORT:0}
spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}